import type { NotificationItem, Report, Store } from './campus';

export const sharedEnabled = Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const base = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
function headers(){return {apikey:key!,Authorization:`Bearer ${key!}`, 'Content-Type':'application/json',Prefer:'return=representation'}}
export async function sharedReports():Promise<Report[]|null>{if(!sharedEnabled)return null;const r=await fetch(`${base}/rest/v1/reports?select=*&order=timestamp.desc`,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error('Shared reports request failed');const rows=await r.json();return rows.map((x:any)=>({id:x.id,edgeId:x.edge_id,type:x.type,location:x.location,description:x.description,timestamp:x.timestamp,updatedAt:x.updated_at,photoName:x.photo_name??undefined,status:x.status,confirmations:x.confirmations??[],createdBy:x.created_by}));}
export async function sharedNotifications():Promise<NotificationItem[]|null>{if(!sharedEnabled)return null;const r=await fetch(`${base}/rest/v1/notifications?select=*&order=timestamp.desc&limit=40`,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error('Shared notifications request failed');const rows=await r.json();return rows.map((x:any)=>({id:x.id,title:x.title,body:x.body,type:x.type,timestamp:x.timestamp,readBy:x.read_by??[]}));}
export async function sharedInsertReport(report:Report){if(!sharedEnabled)return;await fetch(`${base}/rest/v1/reports`,{method:'POST',headers:headers(),body:JSON.stringify({id:report.id,edge_id:report.edgeId,type:report.type,location:report.location,description:report.description,timestamp:report.timestamp,updated_at:report.updatedAt,photo_name:report.photoName??null,status:report.status,confirmations:report.confirmations,created_by:report.createdBy})});}
export async function sharedUpdateReport(report:Report){if(!sharedEnabled)return;await fetch(`${base}/rest/v1/reports?id=eq.${encodeURIComponent(report.id)}`,{method:'PATCH',headers:headers(),body:JSON.stringify({status:report.status,updated_at:report.updatedAt,confirmations:report.confirmations})});}
export async function sharedInsertNotification(n:NotificationItem){if(!sharedEnabled)return;await fetch(`${base}/rest/v1/notifications`,{method:'POST',headers:headers(),body:JSON.stringify({id:n.id,title:n.title,body:n.body,type:n.type,timestamp:n.timestamp,read_by:n.readBy})});}
export function mergeShared(local:Store,reports:Report[],notifications:NotificationItem[]):Store{return {...local,reports,notifications};}
